name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: T01
      id: t01
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: T01
        setup-command: export HOME='/home/runner' && cd Bank && dotnet restore
        command: export HOME='/home/runner' && cd Bank && dotnet test
        timeout: 10
        max-score: 7
    - name: T02
      id: t02
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: T02
        setup-command: ''
        command: ls -l cobertura.png
        timeout: 10
        max-score: 7
    - name: T03
      id: t03
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: T03
        setup-command: ''
        command: ls -l .github/workflows/sonar.yml
        timeout: 10
        max-score: 6
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        T01_RESULTS: "${{steps.t01.outputs.result}}"
        T02_RESULTS: "${{steps.t02.outputs.result}}"
        T03_RESULTS: "${{steps.t03.outputs.result}}"
      with:
        runners: t01,t02,t03
